final<-read.csv("household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors = FALSE, skip=66636, nrows = 2880)
colnames(final)<-names(d1)
final$Date<-as.Date(final$Date, "%d/%m/%Y")
final <- final[complete.cases(final),]
datetime<-paste(final$Date, final$Time)
dateTime <- setNames(dateTime, "DateTime")
final<-cbind(datetime, final)
final$datetime<-as.POSIXct(datetime)
plot(final$Global_active_power~final$datetime, type="l", ylab="Global Active Power (kilowatts)", xlab="")
dev.copy(png, "plot2.png", width=480, height=480)
dev.off()